### ISSUE TITLE
Startup Crash - 1.20.4

### ISSUE THREAD

**Issue by sciguyryan** [Pitan76/AdvancedReborn#21]
Hi.

I've run into a start-up crash when attempting to run the latest version of Advanced Reborn - this crash doesn't generate a crash report, but I've attached a copy of the latest.log here, though it doesn't appear to give much useful information.

[latest.log](https://github.com/Pitan76/AdvancedReborn/files/14816284/latest.log)

**Comment by bastetfurry** [comment]
Can second that, enabling/adding the mod crashes the game on startup.

```
[13:29:30] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:361) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47491(class_7923.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47476(class_7923.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zmp001$fabric-registry-sync-v0$onStart(class_310.java:6294) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:870) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[13:29:30] [Render thread/INFO]: Stopping!
[13:29:30] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1220) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:281) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Comment by PTOM76** [comment]
Fixed
