### ISSUE TITLE
Crash with 1.1.9 on 1 19 4 log included

### ISSUE THREAD

**Issue by Night-Sky1970** [Pitan76/AdvancedReborn#6]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-03-31 09:49:22
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'advanced_reborn'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IncompatibleClassChangeError: Expected static method 'void ml.pkom.mcpitanlibarch.api.client.registry.ArchRegistryClient.registryClientSpriteAtlasTexture(net.minecraft.class_2960)'
	at ml.pkom.advancedreborn.AdvancedRebornClient.onInitializeClient(AdvancedRebornClient.java:28)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Geavanceerde Windows 32 basis-API:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Bibliotheek met elementen voor gebruikerservaring:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto-API32:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:API DLL van DNS Client:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:DLL-bestand voor Windows NT BASE API-client:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:DLL-bestand voor Windows NT BASE API-client:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2302.7 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE voor Windows:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Runtime voor RPC (Remote Procedure Call):10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Gemeenschappelijk DLL-bestand van Windows Shell:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:DLL-bestand voor Windows USER API-client (meerdere gebruikers):10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP-services:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Toepassingscompatibiliteit van de client:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		bcrypt.dll:Windows-bibliotheek van cryptografische primitieven:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM voor Windows:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client-service:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6-client:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		fwpuclnt.dll:API voor FWP/IPsec in gebruikersmodus:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		javaw.exe:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		jna4770036881299450635.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:19.0.1.0:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service-aanbieder:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Shim-provider van e-mailnamen:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:DLL-bestand voor NT-laag:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA-provider:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL-bestand voor prestatiemeterobjecten van Windows-systeem:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP-naamruimteprovider:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell lichtgewicht hulpprogrammabibliotheek:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
		win32u.dll:Win32u:10.0.22621.1413 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT-opslag-API:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:DLL Windows-basistypen:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		ws2_32.DLL:Windows Socket 2.0 32-bits DLL-bestand:10.0.22621.1411 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:19.0.1.0:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 19.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 8869208080 bytes (8458 MiB) / 10485760000 bytes (10000 MiB) up to 20971520000 bytes (20000 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900 12-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.09
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3141
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39844.88
	Virtual memory used (MB): 22158.15
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 39.52
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms10000m -Xmx20000m
	Fabric Mods: 
		advanced_reborn: Advanced Reborn 1.1.9
		alloy_forgery: Alloy Forgery 2.0.19+1.19.4
		allstackable: AllStackable v1.7.0-1.19.4
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.3+mc1.19.4
		architectury: Architectury 8.1.75
		balm-fabric: Balm 6.0.2
		blossom: Blossom 1.0.7
		bookshelf: Bookshelf 18.0.2
		botanypots: BotanyPots 11.0.2
		botanytrees: BotanyTrees 7.0.1
		botarium: Botarium 2.0.5
		brb: Better Recipe Book 1.7.2
		cem: Custom Entity Models 0.7.3
			completeconfig-base: completeconfig-base 2.3.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.3.1
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.2+1.19.3
		cookingforblockheads: Cooking for Blockheads 15.0.1
		creativecore: CreativeCore (Fabric) 2.10.7
			net_minecraftforge_eventbus: eventbus 6.0.4
		debugify: Debugify 1.19.4+1.0
		entity_texture_features: Entity Texture Features 4.3.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential_commands: Essential Commands 0.32.0-mc1.19.4
			ec-core: Essential Commands Core 1.3.0-mc1.19.4
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			playerabilitylib: Pal 1.7.0
		experiencebottler: Experience Bottler 1.19.4+build.1
		extractinator: Extractinator 2.1.0
		fabric-api: Fabric API 0.76.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.52+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.5+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.22+ca5f59aaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.39+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.6+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.2+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.18+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.18
		fallingtree: FallingTree 3.12.1
		farmingforblockheads: Farming for Blockheads 13.0.1
		ferritecore: FerriteCore 5.2.0
		forgeconfigapiport: Forge Config API Port 6.0.2
		framework: Framework 0.6.0
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		geckolib: Geckolib 4.1.2
			com_eliotlash_mclib_mclib: mclib 20
		htm: Hey That's Mine 1.1.8
		immediatelyfast: ImmediatelyFast 1.1.11
			net_lenni0451_reflect: Reflect 1.1.0
		indium: Indium 1.0.15+mc1.19.4
		inventoryprofilesnext: Inventory Profiles Next 1.9.4
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemphysiclite: ItemPhysic Lite (Fabric) 1.6.1
		jade: Jade 10.0.0
		java: Java HotSpot(TM) 64-Bit Server VM 19
		labellingcontainers: Labelling Containers 1.0.0
		libipn: libIPN 2.0.4
		lithium: Lithium 0.11.1
		mcpitanlibarch: MCPitanLib 1.5.7-1.19.4-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		memoryusagescreen: Memory Usage Screen 1.8.1
		mine_treasure_mr: Mine Treasure 1.2.2
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.1.0-rc.4
		mtmechs: Magitek Mechs 1.0.17
		mtr: Minecraft Transit Railway 1.19.4-3.2.1-hotfix-1
		numismatic-overhaul: Numismatic Overhaul 0.2.9+1.19.4
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			stacc: Stacc 1.5.2+pre.1
		openpartiesandclaims: Open Parties and Claims 0.17.2
		owo: oωo 0.10.3+1.19.4
			blue_endless_jankson: jankson 1.2.2
		pfm: Paladin's Furniture 1.1.3
		phosphor: Phosphor 0.8.1
		rainglow: Rainglow 1.0.3+mc1.19.4
			spruceui: SpruceUI 4.2.0+1.19.4
		raised: Raised 1.2.2
		reborncore: Reborn Core 5.7.0
			team_reborn_energy: Energy 3.0.0
		reputation: Your Reputation 0.2.1+jade.1.19
		resourcefulconfig: Resourcefulconfig 1.2.0
		resourcefullib: Resourceful Lib 1.3.1
			com_teamresourceful_yabn: yabn 1.0.2
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		servercore: ServerCore 1.3.5-1.19.4
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.10.0
			libblockattributes: LibBlockAttributes 0.13.0
				libblockattributes_core: LibBlockAttributes (Core) 0.13.0
				libblockattributes_fluids: LibBlockAttributes (Fluids) 0.13.0
				libblockattributes_items: LibBlockAttributes (Items) 0.13.0
			libmultipart: LibMultiPart 0.10.0
			libmultipart_compat: LibMultiPart (Mod Compatibility) 0.10.0
			libnetworkstack: Lib Network Stack 0.9.0
			simple_pipes: SimplePipeTest 0.10.0
		sodium: Sodium 0.4.10+build.24
		spark: spark 1.10.34
		spellbound_weapons_mr: Spellbound Weapons 4.0.2
		techreborn: Tech Reborn 5.7.0
		things: Things 0.3.0+1.19.4
			reach-entity-attributes: Reach Entity Attributes 2.3.1+pre.1+1.19.4
		toms_storage: Tom's Simple Storage Mod 1.5.3
		travelersbackpack: Traveler's Backpack 1.19.4-8.4.0
		travelerstitles: Traveler's Titles 1.19.4-Fabric-3.3.0
		trinkets: Trinkets 3.6.0
		universal-graves: Universal Graves 2.2.1+1.19.4
			common-protection-api: Common Protection API 1.0.0
			hologram-api: Hologram API 0.2.3+1.19.3
			placeholder-api: Placeholder API 2.0.0-rc.1+1.19.3
			polymer-core: Polymer (Core) 0.4.0-pre.2+1.19.4-rc2
				polymer-networking: Polymer (Networking) 0.4.0-pre.2+1.19.4-rc2
					polymer-common: Polymer (Common) 0.4.0-pre.2+1.19.4-rc2
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.4.0-pre.2+1.19.4-rc2
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
			sgui: sgui 1.2.1+1.19.3
		victus: Victus 0.1.12+1.19.4
		waystones: Waystones 13.0.1
		wilderwild: Wilder Wild 1.1.14-Fabric+1.19.4
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			frozenlib: FrozenLib 1.2.0-Fabric+1.19.4
			nbtcrafting: NBT Crafting 2.2.3+mc1.19.4-pre1
		worldedit: WorldEdit 7.2.14+6360-094b734
		xaerominimap: Xaero's Minimap 23.3.2
		xaeroworldmap: Xaero's World Map 1.29.4
		yet-another-config-lib: YetAnotherConfigLib 2.3.0
		yungsapi: YUNG's API 1.19.4-Fabric-3.10.1
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Night-Sky1970** [comment]
on server it works fine it seems.. but on client i did get this crash.. :)

thank you for putting youre time in making youre awesome mod ! verry happy with it :)  

Monique
